src/kernel/CMakeLists.txt, src/kernel/qwbackend.cpp, src/kernel/qwglobal.cpp, src/kernel/qwglobal.h, src/kernel/render/qwrenderer.cpp, src/kernel/render/qwrenderer.h, src/kernel/render/qwtexture.cpp, src/kernel/render/qwtexture.h, src/kernel/types/qwbuffer.cpp, src/kernel/types/qwbuffer.h
Add QWRenderer QWTexture QWBuffer
=> Implement QWRenderer for wlr_renderer

CMakeLists.txt, examples/CMakeLists.txt, examples/tinywl/CMakeLists.txt, examples/tinywl/main.cpp, src/CMakeLists.txt, src/class_template.txt, src/cmake/CMakeConfig.cmake.in, src/cmake/QWlrootsConfig.cmake, src/cmake/pkgconfig.pc.in, src/qwbackend.cpp, src/qwbackend.h, src/render/qwallocator.cpp, src/render/qwrenderer.cpp, src/types/qwbuffer.cpp, src/types/qwbuffer.h, src/types/qwcompositor.cpp, src/types/qwcompositor.h, src/types/qwcursor.cpp, src/types/qwcursor.h, src/types/qwdatadevice.cpp, src/types/qwoutput.cpp, src/types/qwoutput.h, src/types/qwoutputlayout.cpp, src/types/qwoutputlayout.h, src/types/qwscene.cpp, src/types/qwscene.h, src/types/qwsubcompositor.cpp, src/types/qwxdgshell.cpp, src/types/qwxdgshell.h, src/util/qwsignalconnector.h
Add a tinywl example, it like as the tinywl of wlroots.
=> Add an example

examples/tinywl/CMakeLists.txt, examples/tinywl/main.cpp, src/types/qwoutput.cpp, src/types/qwoutput.h, src/types/qwoutputlayout.cpp, src/types/qwxdgshell.cpp
Remove QWOutput::modeChanged/enableChanged follow wlroots 0.17.0.
=> Fix build failed if wlroots>=0.17.0

README.md, README.zh_CN.md
=> Add README.zh_CN.md

examples/tinywl/CMakeLists.txt, src/CMakeLists.txt
=> Fix build on opensuse

.obs/workflows.yml
Test in: https://github.com/peeweep-test/qwlroots-test
Need set webhook
=> Set workflows for open build service

src/qwbackend.cpp, src/qwbackend.h
Add class QWMultiBackend QWDrmBackend QWWaylandBackend QWX11Backend QWLibinputBackend QWHeadlessBackend.
=> Implement multi/drm/x11/wayland/libinput/headless backends

examples/tinywl/CMakeLists.txt, src/CMakeLists.txt
Avoid stable/xdg-shell/xdg-shell.xml not found
=> Check wayland-protocols module as required

src/CMakeLists.txt, src/types/qwxdgdecorationmanagerv1.cpp, src/types/qwxdgdecorationmanagerv1.h
Patch 了 tinywm 进行测试 https://github.com/wineee/qwlbox/commit/b914982e6239daf1a4123dce61ae7ad48f7133f5
foot 符合预期， 在 MODE_SERVER_SIDE 下不使用自己的装饰
=>  Implement QWXdgDecorationManagerV1 form wlr_xdg_decoration_manager_v1 

src/CMakeLists.txt, src/interfaces/qwbufferinterface.cpp, src/interfaces/qwbufferinterface.h
function implementation not yet implemented
=> implement QWBufferInterface from wlr_buffer

src/CMakeLists.txt
wlr_swapchain uses slots as variable value
=> Keyword to disable qt

src/CMakeLists.txt, src/types/qwxdgforeignv1.cpp, src/types/qwxdgforeignv1.h
=> Implement QWXdgForeignV1 from wlr_xdg_foreign_v1

src/qwbackend.h, src/types/qwcompositor.cpp, src/types/qwcompositor.h, src/types/qwcontenttypev1.cpp, src/types/qwcontenttypev1.h, src/types/qwoutput.cpp, src/types/qwoutput.h, src/types/qwoutputlayout.cpp, src/types/qwoutputlayout.h, src/types/qwscene.cpp, src/types/qwscene.h, src/types/qwtabletv2.cpp, src/types/qwtabletv2.h, src/types/qwxdgdecorationmanagerv1.cpp, src/types/qwxdgdecorationmanagerv1.h, src/types/qwxwaylandsurface.cpp, src/types/qwxwaylandsurface.h
continuation of  https://github.com/vioken/qwlroots/pull/125
=> Check underlying type for all c enum

examples/tinywl/main.cpp
Fix tinywl crash when map surface.
=> Fix tinywl can't render to output

examples/tinywl/main.cpp, flake.lock, src/types/qwscene.cpp, src/types/qwscene.h
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4220#b2a16d0583e826f3f845060b72b67ce2be0de03a
=> Update wlroots17 and fix build

flake.lock, src/interfaces/qwrendererinterface.cpp, src/interfaces/qwrendererinterface.h
wlr_renderer begin_buffer_pass change wlr_buffer_pass_options to const
=> Update wlroot 0.17 and fix build

flake.lock, src/render/qwswapchain.cpp, src/types/qwpresentation.cpp, src/types/qwpresentation.h, src/types/qwscene.cpp, src/types/qwscene.h
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4270
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4081
=> Update wlroots 17 and fix build

.obs/workflows.yml
https://github.com/openSUSE/obs-service-tar_scm/issues/478
=> Degrade Fedora Rawhide to 38 in obs ci

src/types/qwcursor.cpp, src/types/qwcursor.h
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4209/
=> Add missing unsetImage for QWCursor

flake.lock, src/interfaces/qwoutputinterface.cpp, src/interfaces/qwoutputinterface.h, src/qwbackend.cpp, src/qwbackend.h
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4182
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4238
=> Fix build with new wlroots 17

src/types/qwscene.cpp, src/types/qwscene.h
Fixes: https://github.com/vioken/qwlroots/issues/190
=> Fix crash at wlr_scene_output_commit

src/qwglobal.h, src/render/qwswapchain.h, src/render/qwtexture.h, src/types/qwdatacontrolv1.h, src/types/qwdatadevice.h, src/types/qwoutput.h, src/types/qwoutputmanagementv1.h, src/types/qwpresentation.h, src/types/qwxcursormanager.h
fix: https://github.com/vioken/waylib/issues/174
cc @YukariChiba
=> Fix waylib can't build with clang++

src/CMakeLists.txt, src/types/qwseat.cpp, src/types/qwseat.h
Drop QWIdle after wlroots 0.17
Drop QWSeat::validaiteGrabSerial
=> Fix build for wlroots dev latest

src/types/qwlayershellv1.h
=> Remove undefined getGeometry in qwlayershellv1.h

flake.lock, src/interfaces/qwbackendinterface.cpp, src/interfaces/qwbackendinterface.h, src/qwbackend.cpp, src/qwbackend.h, src/types/qwbuffer.cpp, src/types/qwbuffer.h, src/types/qwdrm.cpp, src/types/qwdrm.h
log:
- https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4411
- https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4400
=> Fix build with new wlroots 17 

flake.lock, src/types/qwscene.h
API has changed on wlroots 0.17.0. Correct the forward declaration of this function pointer.
Log: fix compilation on wlroots 0.17.0
=> fix: compilation on wlroots 0.17.0

.envrc, .reuse/dep5, default.nix, flake.lock, flake.nix, nix/default.nix, src/types/qwgammacontorlv1.cpp, src/types/qwgammacontorlv1.h, tests/test_qwobject.cpp
1. Make wlroot 17 as default in nix ci 
2. reuse compliant
3. Add missing gammaChanged signal in QWGammaControlManagerV1
=> Make wlroot 17 as default in nix ci and reuse compliant

src/CMakeLists.txt, src/interfaces/qwrendererinterface.cpp, src/interfaces/qwrendererinterface.h, src/render/qwrenderer.cpp, src/render/qwrenderer.h, src/types/qwinputinhibitmanager.h, src/types/qwoutput.cpp, src/types/qwoutput.h
Some functions are totally dropped in 0.18.0
Log: fix api incompatibility on wlroots 0.18.0
=> fix: api incompatibility on wlroots 0.18.0

src/types/qwbuffer.h
=> Add cleanup helper for qw_buffer

src/qwglobal.h
fix： https://build.deepin.com/package/live_build_log/vioken/qwlroots/deepin_23_testing/aarch64
=> Fix build when use gcc <= 12

src/types/qwlayershellv1.h, src/types/qwxdgshell.h
it will call xpg_popup_done/zwlr_layer_surface_v1_send_closed to client and clear resource,should allow compositor to do such things
=> Make layer_surface_v1/xdg_popup's destroy publice

src/CMakeLists.txt, src/qwobject.h, src/types/qwinputdevice.cpp, src/types/qwinputdevice.h, src/types/qwvirtualkeyboardv1.h, src/types/qwvirtualpointerv1.h
Let qw_virtual_keyboard_v1 inherit qw_keyboard.
=> fix: qw_virtual_keyboard inheritance

README.md, README.zh_CN.md
* Update English version;
* Polish Chinese version.
=> chore: update readme

src/types/qwidleinhibitv1.h
https://github.com/linuxdeepin/treeland/pull/387
=> Implement qw_idle_inhibitor_v1

.cursor/rules/public.mdc, .gitmodules, .reuse/dep5, README.md, README.zh_CN.md, analyze_coverage.py, doc/ai/qwlroots-wrapping-patterns-best-practices-en.md, doc/ai/qwlroots-wrapping-patterns-best-practices.md
1. Added `.cursor/rules/public.mdc` to provide instructions for using the Cursor AI tool in the project.
2. Added `.gitmodules` to include the wlroots submodule for better dependency management.
3. Updated `README.md` and `README.zh_CN.md` to reflect wlroots 0.19.x compatibility and provide instructions for updating wrapping coverage. The README files also now include a wrapping coverage status table.
4. Added `analyze_coverage.py` to automate the calculation and update of wrapping coverage based on the wlroots submodule.
5. Added `doc/ai/qwlroots-wrapping-patterns-best-practices-en.md` and `doc/ai/qwlroots-wrapping-patterns-best-practices.md` to document wrapping patterns for AI assistant usage.
docs: 添加AI开发的文档
1. 添加了 `.cursor/rules/public.mdc`，用于在使用 Cursor AI 工具进行项目 开发时提供指南。
2. 添加了 …
=> docs: add documentation for AI development
