vioken/qwlroots

- src/CMakeLists.txt
- src/qwbackend.cpp
- src/qwbackend.h
- src/util/qwsignalconnector.cpp
- src/util/qwsignalconnector.h
Add newInput and newOutput signals.
Add QWSignalConnector class to easier to connect a wl_signal, the class is copy from Waylib's WSignalconnector, it like as Qt signal-slot design.
> Add signals in QWBackend

- src/qwbackend.cpp
- src/qwbackend.h
- src/render/qwrenderer.cpp
- src/render/qwrenderer.h
- src/render/qwtexture.cpp
- src/render/qwtexture.h
- src/types/qwbuffer.cpp
- src/types/qwbuffer.h
Allows to directly  to construct a QW* object by a wlr_* object,  it is more flexible for the developer of qwlroots, he can use qwlroots in part of the code, and use wlroots directly in another part of the code, for example:
// wlroots part, or the wlr_backend object is from another library struct wlr_backend *backend = wlr_multi_backend_create(display); ...
// qwlroots part
auto qbackend = new QWBackend(backend);
Other, move the QW*Private::handle to QW*::handle.
> Allow to construction QW* object

- src/types/qwbuffer.cpp
- src/types/qwcompositor.cpp
- src/types/qwdatadevice.cpp
- src/types/qwoutputlayout.cpp
- src/types/qwscene.cpp
- src/types/qwscene.h
- src/types/qwxdgshell.cpp
Initialization QObject before QWObject at derived class. 
Use QPointF* instead of QPointF& for QWSceneNode::at.
> Fix some irregular code

- .obs/workflows.yml
openSUSE  failed in rpm_lint, we need set SONAME for libqwlroots.so
> Add fedora/opensuse in obs workflows

- examples/tinywl/main.cpp
- src/CMakeLists.txt
- src/interfaces/qwbackendinterface.h
- src/interfaces/qwoutputinterface.h
- src/qwbackend.h
- src/types/qwinputdevice.cpp
- src/types/qwkeyboard.h
- src/types/qwoutput.h
- src/types/qwpointer.h
- src/types/qwtablet.h
- src/types/qwtabletpad.h
When using QWlroots from system by find_package(QWlroots), because the "interface" directory is not install to system, so the project build failed.
> Fix interface/qwbackendinterface.h: No such file or directory

- src/render/qwtexture.cpp
- src/render/qwtexture.h
- src/types/qwcursor.cpp
- src/types/qwoutput.cpp
- src/types/qwoutput.h
- src/types/qwxcursormanager.cpp
- src/types/qwxcursormanager.h
The "delete" behovior in C++ will destroy the pointer(first destroy), and the destruct function of class will call the "wlr_xxxx_destroy" function(second destroy) to destroy the pointer. So, we can't using C++ style API to destroy the wlr_xxxx pointer.
Add the "destroy" function to class and mark the destruct function of class to private.
Allow the "dev" is nullptr in QWCursor::move.
> Fix crash 'double free'

- src/qwbackend.cpp
- src/qwbackend.h
- src/qwdisplay.cpp
- src/qwdisplay.h
- src/qwglobal.h
- src/render/qwallocator.cpp
- src/render/qwallocator.h
- src/render/qwrenderer.cpp
- src/render/qwrenderer.h
- src/types/qwbuffer.cpp
- src/types/qwbuffer.h
- src/types/qwcompositor.h
- src/types/qwcursor.cpp
- src/types/qwcursor.h
- src/types/qwdatadevice.cpp
- src/types/qwdatadevice.h
- src/types/qwinputdevice.cpp
- src/types/qwinputdevice.h
- src/types/qwoutput.cpp
- src/types/qwoutput.h
- src/types/qwoutputlayout.cpp
- src/types/qwoutputlayout.h
- src/types/qwscene.cpp
- src/types/qwscene.h
- src/types/qwseat.cpp
- src/types/qwseat.h
- src/types/qwsubcompositor.cpp
- src/types/qwsubcompositor.h
- src/types/qwxdgshell.cpp
- src/types/qwxdgshell.h
To notify before destroy handle(wlr_*), maybe the compositor needs to disconnect signals of the other QW* objects, avoid using the QW*::handle after the handle destroy.
> Add beforeDestroy signals

- default.nix
- flake.lock
- flake.nix
- nix/default.nix
- src/types/qwcompositor.cpp
1. 升级 nix 构建依赖
2. 使用 nix-filter 过滤不参与构建的文件
3. 修复  qwlroots-qt6-wlroots-git 的构建
> Update flake and filter source code for nix derivation

- src/types/qwoutput.cpp
- src/types/qwoutput.h
The wlroots drop wlr_output_cursor_set_surface in
d933f5204b4723eeb64b3c734d4017067f11811b.
> drop QWOutputCursor::setSurface

- src/qwbackend.cpp
- src/qwbackend.h
wlr_backend_autocreate will create a wlr_multi_backend, If we wapper the backend object to QWBackend, will failed cast from QWBackend to QWMultiBackend at QWMultiBackend::from.
> Fix crash using QWMultiBackend::from

- src/types/qwseat.cpp
- src/types/qwseat.h
底层类型是 uint_32_t, 而不是 int， 但不幸的是，这仍不能用于前置声明
> Check underlying type for c enum

- src/types/qwxdgshell.cpp
- src/types/qwxdgshell.h
fix: https://github.com/vioken/qwlroots/issues/146
> QWXdgToplevel::setParsent to QWXdgToplevel::setParent

- examples/tinywl/main.cpp
- flake.lock
- flake.nix
- src/types/qwcursor.cpp
- src/types/qwcursor.h
- src/types/qwoutput.cpp
- src/types/qwoutput.h
- src/types/qwxcursormanager.cpp
- src/types/qwxcursormanager.h
* **cursor: replace wlr_cursor_set_image() with wlr_cursor_set_buffer()** (!4232):
* `wlr_cursor_set_image()` has been replaced with `wlr_cursor_set_buffer()`
* `wlr_xcursor_manager_set_cursor_image()` has been removed. Compositors should instead use `wlr_cursor_set_xcursor()`
* **output: drop wlr_output_cursor_set_image()** (!4250): `wlr_output_cursor_set_buffer()` can be used instead.cursor: replace wlr_cursor_set_image() with wlr_cursor_set_buffer() ([!4232 (merged)](https://github.com/wlroots/wlroots/-/merge_requests/4232)):
- wlr_cursor_set_image() has been replaced with wlr_cursor_set_buffer()
- wlr_xcursor_manager_set_cursor_image() has been removed. Compositors should instead use wlr_cursor_set_xcursor()
output: drop wlr_output_cursor_set_image() ([!4250 …
> Update nix flake input: nixpkgs and wlroots-git

- src/CMakeLists.txt
- src/qwbackend.cpp
In some pure-wayland distros, x11/xwayland will not be installed.
> Make x11 dependency optional

- src/render/qwrenderer.cpp
- src/render/qwrenderer.h
Emitted when the GPU is lost, e.g. on GPU reset.
Compositors should destroy the renderer and re-create it.
> Add lost single for qwrenderer

- src/types/qwcursor.cpp
fix: https://github.com/vioken/qwlroots/issues/196
> Fix undefined reference to QWLRoots::QWCursor::absoluteToLayoutCoords

- src/CMakeLists.txt
types/qwvirtualkeyboardmanagerv1.cpp is missing from target sources,
which will cause undefined reference when linked by others. Add this
file to SOURCES.
Log: fix missing file from target sources
> fix: missing file from target sources

- src/CMakeLists.txt
- src/types/qwkeyboard.cpp
- src/types/qwkeyboard.h
- src/types/qwkeyboard_p.h
- src/types/qwvirtualkeyboardv1.cpp
- src/types/qwvirtualkeyboardv1.h
wlr_virtual_keyboard_v1 is extended form wlr_keyboard, by object-oriented inheritance we can easily reuse QWKeyboard's signal binding
> Make QWVirtualKeyboardV1 inherit form QWKeyboard

- src/types/qwseat.cpp
When there is none keyboard event, there is no active seat keyboard. Getting keyboard from QWSeat might lead to crash cause getKeyboard() assumes that there is at least one active keyboard in seat.
Log: fix crash getting keyboard
> fix: crash getting keyboard

- CMakeLists.txt
Version 3.21 is strongly recommended for more robust and easy syntax. Version less than 3.5 will soon be out of support.
Log: bump cmake compatibility version
> hore: bump cmake compatibility version

- .obs/workflows.yml
This reverts commit a78eadbfe3a486584838977ecf7bf0c9f5d952bd.
obs-service-tar_scm support python 3.12 now: https://github.com/openSUSE/obs-service-tar_scm/issues/478
> Revert "Degrade Fedora Rawhide to 38 in obs ci"

- examples/tinywl/main.cpp
- src/interfaces/qwoutputinterface.cpp
- src/types/qwoutput.cpp
- src/types/qwoutput.h
- src/types/qwoutputlayout.cpp
- src/types/qwoutputlayout.h
wlr_output_layout_create has changed its signature, now we need the display to create output layout. Just make QWOutputLayout's constructor private and add create() to create from display. wlr_output_init now needs the event loop.
Log: fix compilation on wlroots 0.18.0
> fix: compilation on wlroots 0.18.0

- flake.lock
- flake.nix
[gitlab.freedesktop.org/wlroots/wlroots/-/tags](https://gitlab.freedesktop.org/wlroots/wlroots/-/tags)
> Update nix flake lock to use new wlroots 0.17.1

- src/qwglobal.cpp
For waylib to re-new wsurface on GTK reuse
> Fix: allow reset qwobject's associated data owner

- src/CMakeLists.txt
Fix build error when use qwlroots to a dynamic shared library:
relocation R_X86_64_PC32 against symbol `' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value.
> Hidden c/c++ symbol on default

- src/interfaces/qwbackendinterface.h
- src/interfaces/qwbufferinterface.h
- src/interfaces/qwinterface.h
- src/interfaces/qwkeyboardinterface.h
- src/interfaces/qwoutputinterface.h
- src/interfaces/qwpointerinterface.h
- src/interfaces/qwrendererinterface.h
- src/interfaces/qwswitchinterface.h
- src/interfaces/qwtabletpadinterface.h
Use QW_INTERFACE() macro to define interface implementation on the
derive class, eg:
class Foo : public qw_buffer_interface
{
QW_INTERFACE(end_data_ptr_access, void);
};
> Fix qw_interface

- src/qwobject.h
- tests/qwobject_test/test_qwobject.cpp
Compositor can check some qw_object class's instance if has memory leaks before application quit.
> Allows to get qw_object's instances

- src/util/qwlogging.h
Wrapping log message from wlroots and printing it as a QString adds extra quotes to raw message. This might be confusing when log message itself contains double quotes. Just use qPrintable to forward log.
> chore: forward log instead of wrap

- .cursor/rules/public.mdc
The typo "cmake -B buuild" was corrected to "cmake -B build" in the build command description within the public rules file. This ensures accurate instructions for users attempting to compile the project, preventing potential confusion.
fix: 修复构建命令描述中的拼写错误
在公共规则文件中，将构建命令描述中的拼写错误“cmake -B buuild”更正
为“cmake -B build”。此更改确保用户在尝试编译项目时获得准确的指示，避免可
能的混淆。
> fix: correct typo in build command description
